[2024-12-15T18:33:42.002+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T18:33:42.047+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecobalyse_dag.simulations_data manual__2024-12-15T18:33:28.972281+00:00 [queued]>
[2024-12-15T18:33:42.063+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecobalyse_dag.simulations_data manual__2024-12-15T18:33:28.972281+00:00 [queued]>
[2024-12-15T18:33:42.064+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-12-15T18:33:42.088+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): simulations_data> on 2024-12-15 18:33:28.972281+00:00
[2024-12-15T18:33:42.105+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2904) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-15T18:33:42.108+0000] {standard_task_runner.py:72} INFO - Started process 2950 to run task
[2024-12-15T18:33:42.110+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecobalyse_dag', 'simulations_data', 'manual__2024-12-15T18:33:28.972281+00:00', '--job-id', '1344', '--raw', '--subdir', 'DAGS_FOLDER/data_transformations.py', '--cfg-path', '/tmp/tmpa47iklem']
[2024-12-15T18:33:42.111+0000] {standard_task_runner.py:105} INFO - Job 1344: Subtask simulations_data
[2024-12-15T18:33:42.191+0000] {task_command.py:467} INFO - Running <TaskInstance: ecobalyse_dag.simulations_data manual__2024-12-15T18:33:28.972281+00:00 [running]> on host 8cc0e2e8fe41
[2024-12-15T18:33:42.373+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecobalyse_dag' AIRFLOW_CTX_TASK_ID='simulations_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T18:33:28.972281+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T18:33:28.972281+00:00'
[2024-12-15T18:33:42.375+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-15T18:33:42.375+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-15T18:33:42.376+0000] {logging_mixin.py:190} INFO - Current task name:simulations_data state:running start_date:2024-12-15 18:33:42.048382+00:00
[2024-12-15T18:33:42.376+0000] {logging_mixin.py:190} INFO - Dag name:ecobalyse_dag and current dag run status:running
[2024-12-15T18:33:42.376+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T18:33:54.536+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 47.84 secondes.
[2024-12-15T18:34:55.234+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 47.14 secondes.
[2024-12-15T18:35:55.334+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 47.05 secondes.
[2024-12-15T18:36:55.012+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 47.37 secondes.
[2024-12-15T18:37:54.691+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 47.69 secondes.
[2024-12-15T18:38:55.185+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 47.20 secondes.
[2024-12-15T18:39:55.613+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 46.77 secondes.
[2024-12-15T18:40:54.985+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 47.40 secondes.
[2024-12-15T18:41:57.011+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 45.37 secondes.
[2024-12-15T18:42:55.592+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 46.79 secondes.
[2024-12-15T18:43:55.519+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 46.87 secondes.
[2024-12-15T18:44:55.498+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 46.89 secondes.
[2024-12-15T18:45:56.874+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 45.51 secondes.
[2024-12-15T18:46:56.685+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 45.70 secondes.
[2024-12-15T18:47:56.735+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 45.66 secondes.
[2024-12-15T18:48:55.390+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 47.00 secondes.
[2024-12-15T18:49:56.509+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 45.88 secondes.
[2024-12-15T18:50:57.243+0000] {logging_mixin.py:190} INFO - Limite atteinte, attente de 45.15 secondes.
[2024-12-16T08:21:56.797+0000] {job.py:229} INFO - Heartbeat recovered after 33323.04 seconds
[2024-12-16T08:22:37.365+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2024-12-16T08:22:37.366+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-16T08:22:37.367+0000] {process_utils.py:132} INFO - Sending 15 to group 2950. PIDs of all processes in the group: [2950]
[2024-12-16T08:22:37.367+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2950
[2024-12-16T08:22:37.368+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-16T08:22:37.385+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulations.py", line 46, in generate_simulations
    simulation_result = fetch_simulation(scenario)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulations.py", line 16, in fetch_simulation
    response = requests.post(f"{API_URL}/textile/simulator", headers=HEADERS, json=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-16T08:22:37.393+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-16T08:22:37.393+0000] {logging_mixin.py:190} INFO - Task start:2024-12-15 18:33:42.048382+00:00 end:2024-12-16 08:22:37.392607+00:00 duration:49735.344225
[2024-12-16T08:22:37.393+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): simulations_data> dag:<DAG: ecobalyse_dag> dagrun:<DagRun ecobalyse_dag @ 2024-12-15 18:33:28.972281+00:00: manual__2024-12-15T18:33:28.972281+00:00, state:running, queued_at: 2024-12-15 18:33:28.989920+00:00. externally triggered: True>
[2024-12-16T08:22:37.393+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-12-16T08:22:37.394+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ecobalyse_dag, task_id=simulations_data, run_id=manual__2024-12-15T18:33:28.972281+00:00, execution_date=20241215T183328, start_date=20241215T183342, end_date=20241216T082237
[2024-12-16T08:22:37.409+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-16T08:22:37.460+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2950, status='terminated', exitcode=2, started='18:33:41') (2950) terminated with exit code 2
