[2024-12-15T18:34:22.941+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T18:34:22.987+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecobalyse_dag.simulations_data manual__2024-12-15T18:34:06.556284+00:00 [queued]>
[2024-12-15T18:34:23.013+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecobalyse_dag.simulations_data manual__2024-12-15T18:34:06.556284+00:00 [queued]>
[2024-12-15T18:34:23.014+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-12-15T18:34:23.057+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): simulations_data> on 2024-12-15 18:34:06.556284+00:00
[2024-12-15T18:34:23.078+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3107) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-15T18:34:23.082+0000] {standard_task_runner.py:72} INFO - Started process 3184 to run task
[2024-12-15T18:34:23.084+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecobalyse_dag', 'simulations_data', 'manual__2024-12-15T18:34:06.556284+00:00', '--job-id', '1353', '--raw', '--subdir', 'DAGS_FOLDER/data_transformations.py', '--cfg-path', '/tmp/tmpqckgcw0g']
[2024-12-15T18:34:23.086+0000] {standard_task_runner.py:105} INFO - Job 1353: Subtask simulations_data
[2024-12-15T18:34:23.205+0000] {task_command.py:467} INFO - Running <TaskInstance: ecobalyse_dag.simulations_data manual__2024-12-15T18:34:06.556284+00:00 [running]> on host 8cc0e2e8fe41
[2024-12-15T18:34:23.421+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecobalyse_dag' AIRFLOW_CTX_TASK_ID='simulations_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T18:34:06.556284+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T18:34:06.556284+00:00'
[2024-12-15T18:34:23.424+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-15T18:34:23.424+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-15T18:34:23.424+0000] {logging_mixin.py:190} INFO - Current task name:simulations_data state:running start_date:2024-12-15 18:34:22.988283+00:00
[2024-12-15T18:34:23.425+0000] {logging_mixin.py:190} INFO - Dag name:ecobalyse_dag and current dag run status:running
[2024-12-15T18:34:23.425+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T18:34:23.438+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulations.py", line 32, in generate_simulations
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 15141 column 9 (char 393530)
[2024-12-15T18:34:23.466+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-15T18:34:23.467+0000] {logging_mixin.py:190} INFO - Task start:2024-12-15 18:34:22.988283+00:00 end:2024-12-15 18:34:23.464965+00:00 duration:0.476682
[2024-12-15T18:34:23.468+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): simulations_data> dag:<DAG: ecobalyse_dag> dagrun:<DagRun ecobalyse_dag @ 2024-12-15 18:34:06.556284+00:00: manual__2024-12-15T18:34:06.556284+00:00, state:running, queued_at: 2024-12-15 18:34:06.601171+00:00. externally triggered: True>
[2024-12-15T18:34:23.469+0000] {logging_mixin.py:190} INFO - Failure caused by Expecting property name enclosed in double quotes: line 15141 column 9 (char 393530)
[2024-12-15T18:34:23.469+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ecobalyse_dag, task_id=simulations_data, run_id=manual__2024-12-15T18:34:06.556284+00:00, execution_date=20241215T183406, start_date=20241215T183422, end_date=20241215T183423
[2024-12-15T18:34:23.515+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T18:34:23.517+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1353 for task simulations_data (Expecting property name enclosed in double quotes: line 15141 column 9 (char 393530); 3184)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulations.py", line 32, in generate_simulations
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 15141 column 9 (char 393530)
[2024-12-15T18:34:23.582+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-15T18:34:23.623+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T18:34:23.626+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
