[2024-12-15T15:41:04.478+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T15:41:04.508+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecobalyse_dag.simulations_data manual__2024-12-15T15:38:39.597991+00:00 [queued]>
[2024-12-15T15:41:04.526+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecobalyse_dag.simulations_data manual__2024-12-15T15:38:39.597991+00:00 [queued]>
[2024-12-15T15:41:04.526+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2024-12-15T15:41:04.547+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): simulations_data> on 2024-12-15 15:38:39.597991+00:00
[2024-12-15T15:41:04.560+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=218) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-15T15:41:04.562+0000] {standard_task_runner.py:72} INFO - Started process 241 to run task
[2024-12-15T15:41:04.564+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecobalyse_dag', 'simulations_data', 'manual__2024-12-15T15:38:39.597991+00:00', '--job-id', '1323', '--raw', '--subdir', 'DAGS_FOLDER/data_transformations.py', '--cfg-path', '/tmp/tmpv16gdq3u']
[2024-12-15T15:41:04.566+0000] {standard_task_runner.py:105} INFO - Job 1323: Subtask simulations_data
[2024-12-15T15:41:04.630+0000] {task_command.py:467} INFO - Running <TaskInstance: ecobalyse_dag.simulations_data manual__2024-12-15T15:38:39.597991+00:00 [running]> on host 8cc0e2e8fe41
[2024-12-15T15:41:04.748+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecobalyse_dag' AIRFLOW_CTX_TASK_ID='simulations_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T15:38:39.597991+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T15:38:39.597991+00:00'
[2024-12-15T15:41:04.749+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-15T15:41:04.750+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-15T15:41:04.750+0000] {logging_mixin.py:190} INFO - Current task name:simulations_data state:running start_date:2024-12-15 15:41:04.509438+00:00
[2024-12-15T15:41:04.750+0000] {logging_mixin.py:190} INFO - Dag name:ecobalyse_dag and current dag run status:running
[2024-12-15T15:41:04.750+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T15:41:04.751+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: generate_simulations() missing 1 required positional argument: 'max_requests_per_minute'
[2024-12-15T15:41:04.763+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-15T15:41:04.763+0000] {logging_mixin.py:190} INFO - Task start:2024-12-15 15:41:04.509438+00:00 end:2024-12-15 15:41:04.762699+00:00 duration:0.253261
[2024-12-15T15:41:04.763+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): simulations_data> dag:<DAG: ecobalyse_dag> dagrun:<DagRun ecobalyse_dag @ 2024-12-15 15:38:39.597991+00:00: manual__2024-12-15T15:38:39.597991+00:00, state:running, queued_at: 2024-12-15 15:38:39.638381+00:00. externally triggered: True>
[2024-12-15T15:41:04.764+0000] {logging_mixin.py:190} INFO - Failure caused by generate_simulations() missing 1 required positional argument: 'max_requests_per_minute'
[2024-12-15T15:41:04.764+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ecobalyse_dag, task_id=simulations_data, run_id=manual__2024-12-15T15:38:39.597991+00:00, execution_date=20241215T153839, start_date=20241215T154104, end_date=20241215T154104
[2024-12-15T15:41:04.780+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T15:41:04.780+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1323 for task simulations_data (generate_simulations() missing 1 required positional argument: 'max_requests_per_minute'; 241)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: generate_simulations() missing 1 required positional argument: 'max_requests_per_minute'
[2024-12-15T15:41:04.818+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-15T15:41:04.859+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T15:41:04.865+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
