[2024-12-15T16:22:47.838+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T16:22:47.868+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecobalyse_dag.save_json_file manual__2024-12-15T15:47:08.327050+00:00 [queued]>
[2024-12-15T16:22:47.884+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecobalyse_dag.save_json_file manual__2024-12-15T15:47:08.327050+00:00 [queued]>
[2024-12-15T16:22:47.885+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2024-12-15T16:22:47.908+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_json_file> on 2024-12-15 15:47:08.327050+00:00
[2024-12-15T16:22:47.923+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=844) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-15T16:22:47.925+0000] {standard_task_runner.py:72} INFO - Started process 867 to run task
[2024-12-15T16:22:47.927+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecobalyse_dag', 'save_json_file', 'manual__2024-12-15T15:47:08.327050+00:00', '--job-id', '1328', '--raw', '--subdir', 'DAGS_FOLDER/data_transformations.py', '--cfg-path', '/tmp/tmptw6r92l0']
[2024-12-15T16:22:47.929+0000] {standard_task_runner.py:105} INFO - Job 1328: Subtask save_json_file
[2024-12-15T16:22:48.005+0000] {task_command.py:467} INFO - Running <TaskInstance: ecobalyse_dag.save_json_file manual__2024-12-15T15:47:08.327050+00:00 [running]> on host 8cc0e2e8fe41
[2024-12-15T16:22:48.150+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecobalyse_dag' AIRFLOW_CTX_TASK_ID='save_json_file' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T15:47:08.327050+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T15:47:08.327050+00:00'
[2024-12-15T16:22:48.152+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-15T16:22:48.152+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-15T16:22:48.153+0000] {logging_mixin.py:190} INFO - Current task name:save_json_file state:running start_date:2024-12-15 16:22:47.869526+00:00
[2024-12-15T16:22:48.153+0000] {logging_mixin.py:190} INFO - Dag name:ecobalyse_dag and current dag run status:running
[2024-12-15T16:22:48.153+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T16:22:48.154+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulations.py", line 58, in save_json_file
    simulations = generate_simulations(60)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: generate_simulations() takes 0 positional arguments but 1 was given
[2024-12-15T16:22:48.170+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-15T16:22:48.171+0000] {logging_mixin.py:190} INFO - Task start:2024-12-15 16:22:47.869526+00:00 end:2024-12-15 16:22:48.170070+00:00 duration:0.300544
[2024-12-15T16:22:48.172+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): save_json_file> dag:<DAG: ecobalyse_dag> dagrun:<DagRun ecobalyse_dag @ 2024-12-15 15:47:08.327050+00:00: manual__2024-12-15T15:47:08.327050+00:00, state:running, queued_at: 2024-12-15 15:47:08.362513+00:00. externally triggered: True>
[2024-12-15T16:22:48.172+0000] {logging_mixin.py:190} INFO - Failure caused by generate_simulations() takes 0 positional arguments but 1 was given
[2024-12-15T16:22:48.173+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ecobalyse_dag, task_id=save_json_file, run_id=manual__2024-12-15T15:47:08.327050+00:00, execution_date=20241215T154708, start_date=20241215T162247, end_date=20241215T162248
[2024-12-15T16:22:48.196+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T16:22:48.196+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1328 for task save_json_file (generate_simulations() takes 0 positional arguments but 1 was given; 867)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulations.py", line 58, in save_json_file
    simulations = generate_simulations(60)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: generate_simulations() takes 0 positional arguments but 1 was given
[2024-12-15T16:22:48.221+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-15T16:22:48.276+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T16:22:48.284+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
